"""Reusable region selector for Hyprland."""

from .geometry import (
    CornerRole,
    DockSide,
    Monitor,
    Rect,
    ToolbarPlacement,
    centered_start_rect,
    choose_dock_side,
    corner_points,
    dot_positions,
    drag_corner,
    fit_rect_to_monitor,
    is_fullscreen,
    largest_outside_side,
    monitor_at_position,
    move_rect,
    normalize_rect,
    outside_space,
    place_toolbar,
    reserve_toolbar_space,
    toolbar_fits,
    toolbar_placement,
)
from .hyprland import (
    CursorSocket,
    HyprlandError,
    HyprlandIPC,
    capture_geometry_from_json,
    focused_monitor_from_json,
    match_dot_windows,
    monitor_from_json,
    monitors_from_json,
)
from .selector import RegionSelector, SelectionInteractionMode


__all__ = [
    "CornerRole",
    "CursorSocket",
    "DockSide",
    "HyprlandError",
    "HyprlandIPC",
    "Monitor",
    "Rect",
    "RegionSelector",
    "SelectionInteractionMode",
    "ToolbarPlacement",
    "centered_start_rect",
    "capture_geometry_from_json",
    "choose_dock_side",
    "corner_points",
    "dot_positions",
    "drag_corner",
    "fit_rect_to_monitor",
    "focused_monitor_from_json",
    "is_fullscreen",
    "largest_outside_side",
    "match_dot_windows",
    "monitor_at_position",
    "monitor_from_json",
    "monitors_from_json",
    "move_rect",
    "normalize_rect",
    "outside_space",
    "place_toolbar",
    "reserve_toolbar_space",
    "toolbar_fits",
    "toolbar_placement",
]
